CREATE DATABASE ubuntu4;
USE ubuntu4;

CREATE TABLE Sample (
    id VARCHAR(100) PRIMARY KEY,
    PopulationCode VARCHAR(50),
    PRIMARY KEY(id) 
);

-- Import data from sample.csv


CREATE TABLE Population (
    PopulationCode VARCHAR(255),
    PopulationName VARCHAR(255),
    SuperpopulationCode VARCHAR(50),
    SuperpopulationName VARCHAR(255),
    PRIMARY KEY(PopulationCode)
);

-- Import data from Population.csv

CREATE TABLE SNP_INFO (
	CHROM VARCHAR(50),
    POS int,
    SNP_ID VARCHAR(255),
    REF VARCHAR(255),
    ALT VARCHAR(255),
    GENES VARCHAR(500),
    Clinical_impact TEXT,
    PRIMARY KEY(POS,SNP_ID)
    
);
ALTER TABLE SNP_INFO ADD UNIQUE INDEX idx_snp_id (SNP_ID);
-- Import data from snp_info.zip

CREATE TABLE allele_frequencies (
    SNP VARCHAR(255),
    CHR INT,
    POS INT,
    ALT_FRQ DOUBLE,
    REF_FRQ DOUBLE,
    PopulationCode VARCHAR(255)
);

-- INDEX TABLE allele_frequencies  
CREATE INDEX idx_snp_pos ON allele_frequencies (SNP, POS);


-- paritioning the table by population group 
ALTER TABLE allele_frequencies PARTITION BY LIST COLUMNS(POP)
(
PARTITION p1 VALUES IN ('SIB'),PARTITION p2 VALUES IN ('GBR'),PARTITION p3 VALUES IN ('FIN'),PARTITION p4 VALUES IN ('CHS'),
PARTITION p5 VALUES IN ('PUR'),PARTITION p6 VALUES IN ('CDX'),PARTITION p7 VALUES IN ('CLM'),PARTITION p8 VALUES IN ('IBS'),
PARTITION p9 VALUES IN ('PEL'),PARTITION p10 VALUES IN ('PJL'),PARTITION p11 VALUES IN ('KHV'),PARTITION p12 VALUES IN ('ACB'),
PARTITION p13 VALUES IN ('GWD'),PARTITION p14 VALUES IN ('ESN'),PARTITION p15 VALUES IN ('BEB'),PARTITION p16 VALUES IN ('MSL'),
PARTITION p17 VALUES IN ('STU'),PARTITION p18 VALUES IN ('ITU'),PARTITION p19 VALUES IN ('CEU'),PARTITION p20 VALUES IN ('YRI'),
PARTITION p21 VALUES IN ('CHB'),PARTITION p22 VALUES IN ('JPT'),PARTITION p23 VALUES IN ('LWK'),PARTITION p24 VALUES IN ('ASW'),
PARTITION p25 VALUES IN ('MXL'),PARTITION p26 VALUES IN ('TSI'),PARTITION p27 VALUES IN ('GIH'))

CREATE TABLE genotype_frequencies (
    SNP VARCHAR(255),
    CHR INT,
    POS INT,
    HOM_ALT DOUBLE,
    HOM_REF DOUBLE,
    HET DOUBLE,
    PopulationCode VARCHAR(255)
);

-- INDEXING the table 
CREATE INDEX idx_snp_pos ON genotype_frequencies_frequencies (SNP, POS);

-- partitioning the table by population group 
ALTER TABLE genotype_frequencies PARTITION BY LIST COLUMNS(POP)
(
PARTITION p1 VALUES IN ('SIB'),PARTITION p2 VALUES IN ('GBR'),PARTITION p3 VALUES IN ('FIN'),PARTITION p4 VALUES IN ('CHS'),
PARTITION p5 VALUES IN ('PUR'),PARTITION p6 VALUES IN ('CDX'),PARTITION p7 VALUES IN ('CLM'),PARTITION p8 VALUES IN ('IBS'),
PARTITION p9 VALUES IN ('PEL'),PARTITION p10 VALUES IN ('PJL'),PARTITION p11 VALUES IN ('KHV'),PARTITION p12 VALUES IN ('ACB'),
PARTITION p13 VALUES IN ('GWD'),PARTITION p14 VALUES IN ('ESN'),PARTITION p15 VALUES IN ('BEB'),PARTITION p16 VALUES IN ('MSL'),
PARTITION p17 VALUES IN ('STU'),PARTITION p18 VALUES IN ('ITU'),PARTITION p19 VALUES IN ('CEU'),PARTITION p20 VALUES IN ('YRI'),
PARTITION p21 VALUES IN ('CHB'),PARTITION p22 VALUES IN ('JPT'),PARTITION p23 VALUES IN ('LWK'),PARTITION p24 VALUES IN ('ASW'),
PARTITION p25 VALUES IN ('MXL'),PARTITION p26 VALUES IN ('TSI'),PARTITION p27 VALUES IN ('GIH'))
	

CREATE TABLE GENES (
	GENE VARCHAR(255)
    POS_START INT,
    POS_END INT,
    PRIMARY KEY(GENE)

);
-- Import data from processed_genes.csv 


CREATE TABLE pca_values (
	id VARCHAR(255),
    PC_1 DOUBLE,
    PC_2 DOUBLE,
    PC_3 DOUBLE,
    Population VARCHAR(100),
    PRIMARY KEY(id)

);

-- Import data from pca_values.csv

CREATE TABLE admixture (
	id VARCHAR(255),
    k1 DOUBLE,
    k2 DOUBLE,
    k3 DOUBLE,
    k4 DOUBLE,
    k5 DOUBLE,
    PRIMARY KEY(id)

);

-- Import data from admixture.csv 


